from __future__ import annotations

from enum import Enum


class Severity(str, Enum):
    INFO = "INFO"
    NOTICE = "NOTICE"
    WARNING = "WARNING"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ExceptionKind(str, Enum):
    # Spec taxonomy
    DOCUMENT_EXTRACTION_FAILURE = "DOCUMENT_EXTRACTION_FAILURE"
    LOW_OCR_CONFIDENCE = "LOW_OCR_CONFIDENCE"
    MISSING_SOURCE_PINPOINT = "MISSING_SOURCE_PINPOINT"
    UNSUPPORTED_FACT = "UNSUPPORTED_FACT"
    ALLEGATION_PRESENTED_AS_FACT = "ALLEGATION_PRESENTED_AS_FACT"
    CONTRADICTORY_EVIDENCE = "CONTRADICTORY_EVIDENCE"
    UNRESOLVED_IDENTITY = "UNRESOLVED_IDENTITY"
    UNRESOLVED_DATE = "UNRESOLVED_DATE"
    UNRESOLVED_SERVICE_METHOD = "UNRESOLVED_SERVICE_METHOD"
    HALLUCINATED_AUTHORITY_ATTEMPT = "HALLUCINATED_AUTHORITY_ATTEMPT"
    CITATION_NOT_FOUND = "CITATION_NOT_FOUND"
    PINPOINT_NOT_FOUND = "PINPOINT_NOT_FOUND"
    QUOTATION_MISMATCH = "QUOTATION_MISMATCH"
    ADVERSE_AUTHORITY_NOT_ADDRESSED = "ADVERSE_AUTHORITY_NOT_ADDRESSED"
    STATUTE_VERSION_UNCERTAIN = "STATUTE_VERSION_UNCERTAIN"
    LEGAL_TEST_UNSUPPORTED = "LEGAL_TEST_UNSUPPORTED"
    LEGAL_TEST_CONFLICTED = "LEGAL_TEST_CONFLICTED"
    DEADLINE_CALCULATION_AMBIGUOUS = "DEADLINE_CALCULATION_AMBIGUOUS"
    PRIVILEGE_CLASSIFICATION_UNCERTAIN = "PRIVILEGE_CLASSIFICATION_UNCERTAIN"
    POTENTIAL_PRIVILEGE_DISCLOSURE = "POTENTIAL_PRIVILEGE_DISCLOSURE"
    CROSS_MATTER_ACCESS_ATTEMPT = "CROSS_MATTER_ACCESS_ATTEMPT"
    MODEL_POLICY_VIOLATION = "MODEL_POLICY_VIOLATION"
    COMPETENCY_GATE_FAILURE = "COMPETENCY_GATE_FAILURE"
    CONFLICT_CHECK_FAILURE = "CONFLICT_CHECK_FAILURE"
    # Legacy aliases
    HALLUCINATION_ATTEMPT = "HALLUCINATED_AUTHORITY_ATTEMPT"
    CONTRADICTION = "CONTRADICTORY_EVIDENCE"
    EXTRACTION_CONFIDENCE = "LOW_OCR_CONFIDENCE"
    UNVERIFIED_CITATION = "CITATION_NOT_FOUND"
    PRIVILEGE_RISK = "POTENTIAL_PRIVILEGE_DISCLOSURE"
    OTHER = "MODEL_POLICY_VIOLATION"


DEFAULT_SEVERITY: dict[ExceptionKind, Severity] = {
    ExceptionKind.HALLUCINATED_AUTHORITY_ATTEMPT: Severity.CRITICAL,
    ExceptionKind.CITATION_NOT_FOUND: Severity.HIGH,
    ExceptionKind.PINPOINT_NOT_FOUND: Severity.HIGH,
    ExceptionKind.QUOTATION_MISMATCH: Severity.HIGH,
    ExceptionKind.POTENTIAL_PRIVILEGE_DISCLOSURE: Severity.CRITICAL,
    ExceptionKind.CROSS_MATTER_ACCESS_ATTEMPT: Severity.CRITICAL,
    ExceptionKind.LEGAL_TEST_CONFLICTED: Severity.CRITICAL,
    ExceptionKind.CONFLICT_CHECK_FAILURE: Severity.HIGH,
    ExceptionKind.COMPETENCY_GATE_FAILURE: Severity.HIGH,
    ExceptionKind.LEGAL_TEST_UNSUPPORTED: Severity.WARNING,
    ExceptionKind.CONTRADICTORY_EVIDENCE: Severity.WARNING,
    ExceptionKind.LOW_OCR_CONFIDENCE: Severity.WARNING,
    ExceptionKind.DEADLINE_CALCULATION_AMBIGUOUS: Severity.WARNING,
    ExceptionKind.STATUTE_VERSION_UNCERTAIN: Severity.WARNING,
    ExceptionKind.UNSUPPORTED_FACT: Severity.WARNING,
    ExceptionKind.ALLEGATION_PRESENTED_AS_FACT: Severity.WARNING,
    ExceptionKind.ADVERSE_AUTHORITY_NOT_ADDRESSED: Severity.NOTICE,
    ExceptionKind.DOCUMENT_EXTRACTION_FAILURE: Severity.WARNING,
    ExceptionKind.MODEL_POLICY_VIOLATION: Severity.HIGH,
}
