import type { Citation, ReasoningMode } from "../types";

export interface MockAssistantResult {
  content: string;
  citations: Citation[];
}

export async function getMockAssistantResponse(
  prompt: string,
  mode: ReasoningMode,
  agentName: string,
): Promise<MockAssistantResult> {
  await new Promise((resolve) => window.setTimeout(resolve, 650));

  const normalized = prompt.toLowerCase();
  const focus = normalized.includes("deadline")
    ? "The deadline requires a deterministic calculation using the governing forum, service method, deemed-receipt rule, holidays, and any extension authority. It must remain marked human-review-required until those inputs are confirmed."
    : normalized.includes("evidence") || normalized.includes("contradiction")
      ? "The evidence workflow should separate confirmed facts, allegations, inferences, and unresolved conflicts. Every material statement should link to a page, paragraph, image region, or media timestamp."
      : normalized.includes("draft") || normalized.includes("petition")
        ? "A draft can be structured now, but filing-ready status must remain blocked until the evidence, citations, privilege review, procedural requirements, and human approvals are complete."
        : "I can break this request into evidence, law, procedure, counterargument, and next-action layers while keeping unresolved assumptions visible.";

  return {
    content: `${agentName} · ${mode}\n\n${focus}\n\nThis response is generated by the frontend mock service. The production version must route through the private model, retrieval, citation, consent, and privilege services.`,
    citations: [
      {
        id: crypto.randomUUID(),
        title: "Synthetic Development Source",
        locator: "Interface fixture",
        status: "pending",
      },
    ],
  };
}
